### ISSUE TITLE
Implicit hide animation causes AccessViolationException + Fail fast exception in Windows.UI.Xaml.dll and MinUser.dll

### ISSUE THREAD

**Issue by Sergio0694** [Microsoft/WindowsCompositionSamples#225]
Hello,
I'm having a problem with an exception that is thrown in my app (I know how to reproduce it, fortunately) that I have no idea how to solve.
A few info on the problem:

- The same crash happens in the same way both in Debug and Release mode
- When crashing in Debug mode (without .NET Native), VS doesn't show any kind of error message and the app just closes, and after a few seconds the VS debugger closes too
- When debugging with .NET Native enabled, I manage to get these two info on the exceptions being thrown: [**AccessViolationException**](http://i.pi.gy/AnR4.png) and then (pressing Continue on the debugger) a [**FailFastException**](http://i.pi.gy/GoRN.png)
- ~This issue is possibly related to the `RichEditBox` control I'm using and it happens when calling the 'ITextRange.Move(TextRangeUnit, Int32)' method repeatedly (even though the number of times needed to make the app crash is variable). So, this is possibly related to #223~
It looks like the issue is caused by an implicit composition animation I play whenever I close a popup, removing it works as a workaround for the crash
- None of those exceptions had an available StackTrace in the debugger (could be just because of the .NET Native compiler, I'm not sure)
- The app targets W10 build 10.15063

Anyways, I don't think this is to be expected and right now I have a section of the app that's completely broken because of this and I have absolutely no idea on what to do to solve this problem.
Any help would be really appreciated, thank you in advance!
Sergio

**Comment by Sergio0694** [comment]
I managed to pinpoint the cause of the issue (updated the first post), it looks like the problem is caused by a composition hide animation I play when hiding a popup. If I show/hide that popup too quickly and too many times this exception happens.

[**This is the code**](https://github.com/Sergio0694/UICompositionAnimations/blob/master/UICompositionAnimations/CompositionExtensions.cs#L270) for the implicit hide animation.
Hope it will help!

**Comment by Sergio0694** [comment]
I've created a [crash dump](https://1drv.ms/u/s!AjTEhZcuNvx2vfNPbV01VhXK4SyXrw) with the app compiled in Debug with .NET Native (when the crash happens without the .NET Native toolchain enabled, VS doesn't let me create a crash dump).

I hope this might help investigate the issue! 👍

**Comment by shandilvarun** [comment]
Hi @Sergio0694, apologies from a late response. I am investigating this issue now. I will respond back to you as soon as possible with an update or questions. Thanks!

**Comment by Sergio0694** [comment]
@shandilvarun Hello, I realized the link to the animation code was pointing to the wrong line, as I had updated that file after creating the link, and forgot to update it.
It should be right now, and pointing to the method used to setup the implicit animation causing the crash.
Hope it helps, thank you for your time! 😊

**Comment by stmoy** [comment]
Hi @Sergio0694 - we made some changes in these code paths as a part of the development for the next version of Windows. Can you please try out the broken scenario using an insider build and let us know if the issue still occurs?

**Comment by scott-moore-ms** [comment]
@Sergio0694 - I was wondering if you were still seeing this issue?

**Comment by Sergio0694** [comment]
Hey @scott-moore-ms - yeah sorry for the late reply, I'll try this again and see if the issue is no longer there 😄
