### ISSUE TITLE
Target element is null when attaching XamlLight to it in XAML

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsCompositionSamples#244]
When attaching a `XamlLight` object to an element inside a `ControlTemplate` like this

```
<Rectangle x:Name="HoverBackground" Fill="Transparent">
    <Rectangle.Lights>
        <lights:HoverXamlLight />
    </Rectangle.Lights>
</Rectangle>
```
This override method is then called

`protected override void OnConnected(UIElement newElement)`

But `newElement` is `null`. So I have to manually attach the light in code. I wonder if this is by design? Should the light only be applied when the element is instantiated?

I am using Build *16273* and SDK *16267*.

**Comment by daneuber** [comment]
Hi @JustinXinLiu thanks for bringing this to our attention. We've investigated this and are tracking this internally, and will reply back here when an update is available.

**Comment by h82258652** [comment]
I got same problem
![snipaste_2018-08-20_19-29-23](https://user-images.githubusercontent.com/5144550/44338092-73924d00-a4af-11e8-9339-023d77232731.png)
Build 17134.228 and SDK 17134

And here is my code:
```XAML
<Grid Width="100" Height="100" Background="Red">
    <Grid.Lights>
        <local:AmbLight></local:AmbLight>
    </Grid.Lights>
</Grid>
```
I try to change Grid to Border, but the newElement still is null.

**Comment by h82258652** [comment]
After I add x:Name to the Grid control, the newElement is not null. What a strange bug.

**Comment by stmoy** [comment]
Thank you for reporting this issue. We've added it to the XAML framework backlog. In the meantime, it appears that adding an x:Name to the element works around the issue. Closing the issue for now since there is a workaround.
