### ISSUE TITLE
Conceptual > Blur Playground > Blur Amount > moving past 99 causes crash

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/WindowsCompositionSamples#250]
As per the title, going into the Conceptual > Blur Playground section and moving the Blur Amount slider all the way to the right (past 99 specifically) immediately causes the app to crash.

This is on Windows 10 build 15063.674, app version 1.1.19.0

Mitigation: cap the slider

Resolution:  no idea why it crashes

**Comment by likuba** [comment]
Hey @kmgallahan!  Thanks for reporting all these issues.  Unfortunately, we're not currently able to reproduce this one.  Are you using the version of the app downloaded from the Store?  Or are you synced to an older version of this repro and are building locally?

Also just to double check--are you leaving all of the other settings the same (like the dropdown on multiply, color sliders on defaults, and animation toggle to off)?

**Comment by kmgallahan** [comment]
Hi @likuba. This was using the app as found via the Store, and using version 1.1.19.0 as the initial comment mentions.

Also as mentioned, that was using Windows 10 build 15063.674. I could repro the issue multiple times after freshly launching the app and without touching anything else.

However, today after updating to Windows 10 build 16299.15 via the Fall Creators Update I can no longer repro this anymore. Previously the slider would not even indicate that the "100" value was reached in the tooltip - it would just halt at 99 and be proceeded by a crash of the app.

Not planning to go back to the previous version of Windows 10, so I won't be able to try it again there any time soon. A VM install might be adequate testing grounds though.

**Comment by daneuber** [comment]
@kmgallahan We are still unable to reproduce this; can you verify this still repros on the latest version of the Sample Gallery in the Store?

**Comment by kmgallahan** [comment]
@daneuber 
@likuba 

Finally made a connection that identifies the most likely cause of this crash, as well as two other crashes in the Windows Composition Samples app. Moving any of these sliders all the way to the right causes crashes:

- Blur Playground > Blur Amount
- Shadow Playground > Blur Radius or Opacity
- Video Playground (with a file loaded) > any sliders

The issue "[Many layout problems and at least one bug caused by layout rounding](https://github.com/microsoft/microsoft-ui-xaml/issues/1441)" was just created in the WinUI repo.

I can indeed confirm that the crashing only occurs when my system scaling is specifically set to 125% (other values seem fine). This explains why you haven't been able to repro the crashes yet.

Definitely need to investigate this and any other hidden bugs caused by layout rounding.

**Comment by daneuber** [comment]
@kmgallahan thanks for bringing this up again and linking the two. That's a great find! We'll coordinate with XAML to stay on top of their investigation and update when there's a fix available. Thanks!
