### ISSUE TITLE
Feature Request: Support the mouse's back button

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/WindowsCompositionSamples#253]
Currently, viewing any of the samples requires that you click the back button at the top left to return to the related samples.

Supporting the mouse's back button would make navigation much easier, at least for keyboard+mouse users.

**Comment by daneuber** [comment]
Hi @kmgallahan thanks for your feedback! We'll look into this during next round of sample gallery updates. In the mean time if you or someone else want to take a look and submit a PR we'd be happy to take a look.

**Comment by h82258652** [comment]
especially the WebView, I still can not find a way to implement it.
