### ISSUE TITLE
CreateHostBackdropBrush does it work?

### ISSUE THREAD

**Issue by harrypotter06** [Microsoft/WindowsCompositionSamples#260]
Hello,

for "Acrylic" i use under Windows 16299:
Windows.UI.Xaml.Media.AcrylicBrush myBrush = new Windows.UI.Xaml.Media.AcrylicBrush();
 myBrush.BackgroundSource = Windows.UI.Xaml.Media.AcrylicBackgroundSource.HostBackdrop;
 myBrush.TintColor = Color.FromArgb(255, 255, 255, 255);
 myBrush.FallbackColor = Color.FromArgb(255, 255, 255, 255);
 myBrush.TintOpacity = 0.26999999396503;
  Grid1.Background = myBrush;

But for older Versions, i understand that i need CreateHostBackdropBrush?
So i can't found a solution that work like Build 16299.
What must i do?

**Comment by sohchatt** [comment]
AcrylicBrush is only available in the Fall Creators Update.

BackdropBrush is one of the ingredients that goes into building Acrylic material's effect graph; it is not a substitute for the Windows.UI.Xaml.Media.AcrylicBrush. As such, it isn't accessible through markup, doesn't have policies built in for themes and accessibility, doesn't respect the user's power settings and transparency preferences, and so on. To recreate Acrylic material yourself for a Windows build prior to the Fall Creators Update, you will need to build a CompositionEffectBrush with an effect graph that is similar to Acrylic's, and then wrap it in a XamlCompositionBrushBase. You may then expose the relevant properties (such as TintColor, FallbackColor, etc.) as DependencyProperties from your XCBB class and use it in markup.

I believe Sergio0694 in #218 built a custom brush that behaves like acrylic for the Creators Update. Feel free to use that thread to start a discussion with him.

**Comment by harrypotter06** [comment]
Hello @sohchatt okay, but Microsoft self use "Acrylic" on Builds older 16299. So i am searching samples, how Microsoft do that. Will Microsoft more popularity for the fluent design, you should give the developers the opportunity to use this in older Windows 10 Builds ore Fluent-Disign is dead, bevor starts to live.

@daneuber whats the solution from Microsoft? Microsoft self use Fluent in Apps that are for older Windows Version (like WM10, 1703 etc ...)

Devs has one Focus. The App must be run on many devices. Windows 10 16299 has many Bugs. 
So Microsoft must give the devs a solution. At this Moment, i think, "Fluent" on W10 Builds older 16299 are a top secret by Microsoft and Microsoft will not, that devs can use it. So devs must develops his apps w/o Fluent and that for the next years. consistently: Fluent is dead before it lived.

**Comment by daneuber** [comment]
Hi @harrypotter06 thanks for your feedback. We recognize that maintain backwards compatibility is important to app developers, and in the [Acrylic Style Guide](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic) we recommend developers include a check for the API and fallback to a different effect if it is unavailable. At this time developers cannot use a given API in a build earlier than it was released. However, Composition APIs support a number of very configurable effects that can be used instead, depending on your specific UI scenario. If you're interested in mimicking acrylic in earlier builds, please give the solution @sohchatt gave a try. He is a member of MS org monitoring this repo and is very qualified to provide guidance and feedback.

**Comment by harrypotter06** [comment]
@daneuber 
Questin: Why can't you give me code sample how Microsoft implement Fluent Design in Apps, that are not Build for Win 10 16299? 

@sohchatt : You link, the Code did not work. Think the code is from older Visual Studio Versions. We use 2017! Example: [NotNull] did not work.

Wahts the result from this day: Fluent Design waht Microsoft use on his Apps for older Versions from Windows, is a top secret and not public for developers. 
Thats not a good Image, Microsoft. Did my customer ses this ... oh oh, not good for Microsoft

**Comment by sohchatt** [comment]
We understand that backwards compatibility has been a pain-point for developers, @harrypotter06. With the [Windows UI library](https://blogs.windows.com/buildingapps/2018/07/23/windows-ui-library-preview-released/) (released with the October 2018 update), we've tried to fix this problem by making several of our newer controls and resources available on older versions of Windows 10. 

Microsoft.UI.Xaml.Media.AcrylicBrush (`https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.media.acrylicbrush`) is now supported with transparency effects on version 10.0.15063 and above. We hope that you can now bring the benefits of Acrylic to all your customers on all versions of Windows. 

As always, thanks a lot for your feedback and helping us improve our platform. I'm marking this issue as resolved for now; do let us know if you need any further assistance.
