### ISSUE TITLE
Very difficult to implement that demos

### ISSUE THREAD

**Issue by jmtt89** [microsoft/WindowsCompositionSamples#266]
Maybe i do not understand the purpose of this repository, i thinking the objective are show the demo of custom functionality that Microsoft think is a good design practice and put accesible to others developers for a easy integration on theirs projects.

But is really hard full integrate some of that demos on our current projects... because all demos depends off Samples Common...

I understand you do that for simplify the development but if you really want other people adapt some of that demos for other projects, i think your have two paths...

First one, put a SampleCommon or similar Library on NuGet.

Second, make all demos independent.. so everyone can grab and put the demo on other project and all will work.

**Comment by wldevries** [comment]
I completely agree. It is disappointing that the compositor is introduced as C# and XAML friendly, while the demo applications depend on C++ libraries that do most of the work.

**Comment by wldevries** [comment]
The main problem is that loading bitmaps into brushes is not supported. I first messed around with bits copied from the sample project, but today I found a nuget package that seems to work quite well: [CompositionSurfaceFactory](https://github.com/robmikh/compositionsurfacefactory)

**Comment by salihyildirim2** [comment]
neyin kafası bu

Wouter <notifications@github.com>, 25 Eyl 2020 Cum, 22:10 tarihinde şunu
yazdı:
