### ISSUE TITLE
Slack channel for open Windows UI discussions?

### ISSUE THREAD

**Issue by Massimo37** [Microsoft/WindowsCompositionSamples#298]
Quick question, is there a open Slack channel where devs interested in Windows UI can have discussions?

**Comment by daneuber** [comment]
@Massimo37 Unfortunately as of now one does not exist, but depending on what topics you're interested in, you might try interacting via twitter using '[#uwp](https://twitter.com/hashtag/uwp?src=hash)' and '[#fluentdesign](https://twitter.com/hashtag/fluentdesign?src=hash)' and following posts by '[@MicrosoftDesign](https://twitter.com/MicrosoftDesign)' and '[@WindowsUI](https://twitter.com/windowsui)'. There is also a general [Windows discussion board ](https://answers.microsoft.com/en-us/windows/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1) but its not UI specific.

**Comment by Massimo37** [comment]
Good to know, thanks @daneuber !

**Comment by tomzorz** [comment]
@Massimo37 there is one large windows development slack windev.slack.com ran by @ceee if I'm not mistaken, you can ask him for an invite. (or maybe on twitter https://twitter.com/tobithefox)

I'm also running http://msdev.chat/ but it's a more general MS talk.

**Comment by ceee** [comment]
Thanks @tomzorz.
Yes, @Massimo37, there's a slack for Windows development. Let us know if you wanna join ;-) Either here or on twitter.

**Comment by charlesroddie** [comment]
@ceee How can I join windev.slack.com?

**Comment by ceee** [comment]
@charlesroddie The Slack channel isn't active anymore. Check discord instead: https://uwpcommunity.com/
