### ISSUE TITLE
System.NotImplementedException after adding layer or light in MaterialCreator

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/WindowsCompositionSamples#299]
## Issue Type
[x] Bug Report   

## Current Behavior
MaterialCreator crashes when clicking the "+" button for "Add layer" or "Add light".

The error message is
```
System.NotImplementedException: The method or operation is not implemented.
   at MaterialCreator.LayerControl.LayerControl_obj1_Bindings.ProcessBindings(Object item, Int32 itemIndex, Int32 phase, Int32& nextPhase)
```

## Expected Behavior
Adding a layer or light without a crash

## Steps to Reproduce (for bugs)

1.  Clone this repo
2.  Retarget the MaterialCreator solution to the 17763 SDKs
3.  Run the MaterialCreator app
4.  Click the "+" button for "Add layer"

##  Your Environment

* SDK #:  17763
* Operating System build # :  Windows 10 build 17763
* Visual Studio Version # : 15.9 Preview 3

**Comment by daneuber** [comment]
@hansmbakker Thanks for the feedback! We've pushed updates that fix this issue on our end - can you let us know if these work on your end as well?
