### ISSUE TITLE
InteractionTracker: move contents rather than widget?

### ISSUE THREAD

**Issue by adrientetar** [Microsoft/WindowsCompositionSamples#302]
So I use an InteractionTracker with a Win2D canvas control to make an infinite canvas (with zoom/pan).

When I transform the canvas' Visual, it moves the canvas widget around in the window. I'm looking to rather move (scale/zoom) the contents, without changing the geometry of the widget (sort of like the zoom in Edge I guess). How can I do that?

Code for reference: [https://github.com/adrientetar/Fonte](https://github.com/adrientetar/Fonte/blob/master/Fonte.App/Controls/DesignCanvas.xaml.cs#L69)

RS5/17763

**Comment by adrientetar** [comment]
Btw, I strumbled upon [UIElement.RegisterAsScrollPort](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.registerasscrollport) where docs say:

> This method is intended for use by custom controls that do not use the platform's native controls to display a scrollable area. For example, a custom scrolling control could be built using InteractionTracker.

That sounds like what I'm looking for, I don't fully understand what this method does though. Is there a snippet out there using RegisterAsScrollPort?

**Comment by adrientetar** [comment]
cc @crutkas if you can provide more info on how to use UIElement.RegisterAsScrollPort.

**Comment by crutkas** [comment]
@adrientetar did you leave this feedback on the doc's page?  Bottom right has a popup for "was this page helpful".  Looking at this, I see Danielle assigned to Lindsay which would have been some of the first people i would have asked so you're in good hands.

Good job also providing a repro

**Comment by adrientetar** [comment]
Thanks for looking at this, @likuba.

As you said I'm using InteractionTracker to scroll the canvas.

In the initial position it looks like this (in blue, I'm drawing a selection rectangle with the mouse):

![image](https://user-images.githubusercontent.com/1250894/48951240-1985a580-ef3e-11e8-9b43-a1a1039d374c.png)

When I scroll though, the drawing is clipped to the original viewport – the selection rectangle won't draw all the way to the edge:

![image](https://user-images.githubusercontent.com/1250894/48951312-5b165080-ef3e-11e8-97be-012eab9e50a4.png)

I would like that when I scroll, I can still draw on all visible viewport. So I tried to make the canvas size much larger than viewport size, but the drawing area is still limited to original viewport.

Can InteractionTracker behave like ScrollViewer, where scrolling around can display more content?

**Comment by micahl** [comment]
The [Windows UI Library](https://github.com/microsoft/microsoft-ui-xaml) contains an InteractionTracker-based scrolling control.  You _could_ take a look at its code to see what its doing, or you could use it directly and save quite a bit of effort and code rather than create a custom scrolling control.  
In fact, here's [a fork of your repo that I modified to use the WinUI Scroller](https://github.com/micahl/Fonte/commit/12d400a1b088a885ca7edf6092c9233bf5b620de).  It addresses the issue you initially raised.  It also enables zooming via mousewheel as well as more natural motion by default.  The caveat here is that the control is in 'preview' so its API may (very likely) change in the future.

**Comment by adrientetar** [comment]
Wow! thanks so much Micah. Guess I'll be using Scroller *and* looking at the code to see how it works (;

Btw, are you guys gonna post pm specs for this control? Looking at [this PR](https://github.com/Microsoft/microsoft-ui-xaml/pull/61), will Scroller stop being exposed in favor of ScrollerView?

**Comment by micahl** [comment]
I posted a new proposal that should start to address your question.  Take a look and feel free to comment / ask more questions.  

[Proposal: A more flexible ScrollViewer](https://github.com/Microsoft/microsoft-ui-xaml/issues/108)
