### ISSUE TITLE
ExpressionBuilder NuGet package

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/WindowsCompositionSamples#303]
I see the ExpressionBuilder project is used in multiple projects; would it make sense to create a NuGet package for it?

**Comment by likuba** [comment]
This should be available through the Windows Community Toolkit.  You can learn more about how to use it here: https://docs.microsoft.com/en-us/windows/communitytoolkit/animations/expressions

**Comment by hansmbakker** [comment]
That helps, thank you!
