### ISSUE TITLE
ColorSlideTransition null at colorByPivotItem

### ISSUE THREAD

**Issue by Strypper** [microsoft/WindowsCompositionSamples#310]
## Issue Type

[ ] Bug Report   
[ ] Feature Request   
[ ] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Steps to Reproduce (for bugs)

1.  
2.  
3.  

##  Your Environment

* SDK #:  
* Operating System build # :  
* Visual Studio Version # :

**Comment by daneuber** [comment]
Hi @Strypper could you provide details on which project you found this on and some repro steps?
