### ISSUE TITLE
Visual Layer learning

### ISSUE THREAD

**Issue by assassin316** [microsoft/WindowsCompositionSamples#311]
The Visual Layer (composition api) is great framework for UI development, but can have a higher learning curve for new developers. You should consider putting together a series of videos to help newcomers, as was done with UWP:

[https://channel9.msdn.com/Series/Windows-10-development-for-absolute-beginners](https://channel9.msdn.com/Series/Windows-10-development-for-absolute-beginners)

**Comment by daneuber** [comment]
@assassin316 Thanks for the feedback, we'll take this into consideration! Is there a particular topic you feel should have more coverage or just a general 'intro to composition' series? In the mean time we do have some recorded BUILD talks (here are a few: [1](https://channel9.msdn.com/events/Build/2015/2-672?term=composition%20ui&lang-en=true&pageSize=15&skip=15), [2](https://channel9.msdn.com/events/Windows/Developers-Guide-to-Windows-10-Version-1511/Creating-fluid-and-beautiful-UI-using-the-new-Visual-Layer?term=composition%20ui&lang-en=true), [3](https://channel9.msdn.com/events/Build/2016/P492?term=composition&lang-en=true), [4](https://channel9.msdn.com/events/Build/2017/B8037?term=kelly%20lindsay&lang-en=true), [5](https://channel9.msdn.com/events/Visual-Studio/Visual-Studio-2017-Launch/APP-105?term=david%20li&lang-en=true), [6](https://channel9.msdn.com/events/Build/2017/P4173?term=david%20li&lang-en=true), [7](https://channel9.msdn.com/events/Build/2017/B8100?term=composition%20ui&lang-en=true), [8](https://channel9.msdn.com/events/Build/2018/BRK3503?term=composition%20ui%20sohum&lang-en=true)) and [overview docs](https://docs.microsoft.com/en-us/windows/uwp/composition/visual-layer) which may be helpful.

**Comment by assassin316** [comment]
Those are great resources, thanks. I just feel that there should be videos broken down into specific sections: Visual Layer Intro, Scalar Animations, Effect Animations, Implicit Animations, Expression Builder, EffectBrush, etc....

More importantly, it would be nice to have an order to the videos so that a developer can learn the topics in a proper order (just like they did in the above XAML videos).
