### ISSUE TITLE
[Question] DirectComposition API

### ISSUE THREAD

**Issue by HppZ** [microsoft/WindowsCompositionSamples#313]
Can I use DirectComposition API in Windows Runtime Component written in C++ for UWP project?
or
How to use Direct2d API to do animations like moving a text alone X axis? I use SetTransform and DrawTextLayout to update the text position 60 FPS, but looks not very good.

**Comment by HppZ** [comment]
@daneuber

**Comment by nerddawg** [comment]
> Can I use DirectComposition API in Windows Runtime Component written in C++ for UWP project?

You can use DirectComposition API in a Windows Runtime Component written in C++. As Direct Composition is a desktop API, the component/UWP app will only run on desktop and not truly be universal across Windows devices. Is there a reason it has to be Direct Composition though? You should really consider using the Visual layer (Windows.UI.Composition) APIs as they mostly subsume scenarios supported by Direct Composition and work universally across Windows devices. Let us know if a particular scenario supported in Direct Composition isn't possible with Windows.UI.Composition APIs.

> How to use Direct2d API to do animations like moving a text alone X axis? I use SetTransform and DrawTextLayout to update the text position 60 FPS, but looks not very good.

You can draw Direct 2D text onto a CompositionDrawingSurface (details [here](https://docs.microsoft.com/en-us/windows/uwp/composition/composition-native-interop)) then create a CompositionSurfaceBrush out of it, and animate that (details [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositionsurfacebrush)). The Visual layer's animation engine is far superior to any predecessor animation approaches in Windows, is the focus for our current and future animation investments, and you will easily get the smooth results you are seeking with powerful customization options. 

Iirc @ajbennet and @HarneetSidhana are working on a Direct 2D interop sample and could give a pointer if ready.

**Comment by ajbennet** [comment]
I don't have an official sample yet, but below is a quick sample that animates text along the X axis, that I put together for this. The sample uses the methodology that Ashish(@nerddawg) mentioned above. Please check this out and let me know if this is what you were looking for? 

https://github.com/ajbennet/wincomp-cppwinrt/tree/master/UWP/Direct2DInterop

**Comment by HppZ** [comment]
The sample you provided is really awesome. it avoids redrawing TextLayout.

Windows.UI.Composition supports DropShadow, but does d2d support DropShadowfor TextLayout?
I want to apply shadow effet to text, then animate the text along X axis.

doc from https://docs.microsoft.com/en-us/windows/desktop/Direct2D/effects-overview says:
> **You can apply effects** to any bitmap, including: images loaded by the Windows Imaging Component (WIC), primitives drawn by Direct2D, **text from DirectWrite,** or scenes rendered by Direct3D.

but no doc about how to apply shadow effect to text? only thing I found is https://docs.microsoft.com/en-us/windows/desktop/DirectWrite/how-to-add-custom-drawing-efffects-to-a-text-layout

REALLY thanks for your help!

**Comment by HppZ** [comment]
@ajbennet another thing: does Windows.UI.Composition support outline for Text?

**Comment by ajbennet** [comment]
Windows.UI.Composition is a successor to DirectComposition and is not built on DirectComposition.

There are a couple ways to do this, using D2D's Shadow effect or use Windows.UI.Composition's DropShadow effect for more advanced scenarios like animating shadows etc.. It would be good to understand your scenario better. Do you have a screenshot/capture of what you re  on what you re trying to achieve?

**Comment by HppZ** [comment]
1, I know Windows.UI.Composition supports shadow. but how to implement outline effect in Windows.UI.Composition?

2, How to implement shadow effect and outline effect respectively in D2D?

3, For outline effect in D2D, is it the best option to convert text to GlyphRun and then DrawGeometry?
as does in this link: [docs.com](https://docs.microsoft.com/en-us/windows/desktop/DirectWrite/how-to-add-custom-drawing-efffects-to-a-text-layout#step-3-implement-a-custom-text-renderer-class)

shadow:
![shadow](https://user-images.githubusercontent.com/12285582/51026253-10719600-15c9-11e9-8b7d-fabefe90f017.png)

outline:
![outline](https://user-images.githubusercontent.com/12285582/51026259-14051d00-15c9-11e9-9d9b-d64a221779a8.png)

**Comment by ajbennet** [comment]
**Shadow:** 
Drop shadow can be achieved easily using DropShadow API in WinComp, applied to the SpriteVisual using the SurfaceBrush as the mask. In the sample I shared before, the following will do the job. 

```
DropShadow textShadow{ m_compositor.CreateDropShadow() };
textShadow.BlurRadius(6);
textShadow.Mask(surfaceBrush);
textShadow.Color(Colors::Black());
textShadow.Offset({ 5.0f, 5.0f, -5.0f });
spriteVisual.Shadow(textShadow);
```
** @Outlines:**
Getting outlines a slightly more involved implementation. We will have to leverage [DirectWrite's custom renderer](https://docs.microsoft.com/en-us/windows/desktop/DirectWrite/how-to-implement-a-custom-text-renderer) approach by implementing the IDWriteTextRenderer interface and providing an implementation for the DrawGlyphRun method. IDWriteFontFace::GetGlyphRunOutline gets the outline and you can draw the geometry using DrawGeometry and FillGeometry methods. 
I ve updated the sample [here](https://github.com/ajbennet/wincomp-cppwinrt/tree/master/UWP/Direct2DInterop) to use this approach. 

P.S: Please ignore dead code and sub-optimal coding standards in the above sample, as it was written quickly to get something sooner to you.

**Comment by HppZ** [comment]
👍 thanks for your great help!

**Comment by ajbennet** [comment]
@HppZ  : I have a few questions for you, so we can build the right features.
1) Was there a reason you wanted to use DirectComposition or Windows.UI.Composition in your UWP app instead of XAML controls like the [TextBlock ](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.TextBlock)? 
2) Is memory footprint a concern for your product?
3) Are there any other scenarios where you think Windows.UI.Composition may be preferred over XAML?

**Comment by HppZ** [comment]
We build a UWP app for online video streaming service which supports [barrage/DanMu](https://www.facebook.com/notes/the-sound-of-china/why-danmu-is-so-popular-in-china/1095179960504770/).

1, TextBlock and Storyboard is a choice to do it, but we need advanced effects such as outlined text which is not possible using XAML controls at this moment, Windows.UI.Composition animation is more customizable than Storyboard animation, and performance is also a reason for not using that combination, so lower level APIs come to play.

2, Memory footprint is not a big concern, but lower is better, of course.

3, Maybe 3D/particle and more support in the future. In my opinion, advanced graphic support is a good thing for building better UI/UE modern UWP apps.


All aim to one thing: more fluent experience.
