### ISSUE TITLE
Animating a ListViewItem occurs too late...

### ISSUE THREAD

**Issue by assassin316** [Microsoft/WindowsCompositionSamples#316]
I'm having trouble animating a ListViewItem using the CCC event. I was under the assumption that this event would allow me to start an animation before the item is show on the UI, but the animation is starting too late and doesn't give the desired effect. I have the details in this post (including a GIF):

[https://stackoverflow.com/questions/54205815/how-can-a-listviewbase-animation-be-improved?noredirect=1#comment95282181_54205815](https://stackoverflow.com/questions/54205815/how-can-a-listviewbase-animation-be-improved?noredirect=1#comment95282181_54205815)

Am I going about this the right way?

Thanks!

**Comment by stmoy** [comment]
Hi @assassin316 - I posted a reply on the StackOverflow. I suspect that the default ListView animation is playing first and then the custom animations are playing afterwards. Can you try removing the ListView default ItemContainerTransitions?

**Comment by stmoy** [comment]
Awesome - happy to help. Closing this issue.
