### ISSUE TITLE
Support for Skew transforms?

### ISSUE THREAD

**Issue by assassin316** [Microsoft/WindowsCompositionSamples#319]
So the composition api easily supports animations for rotation, translation, opacity, and scale, but what about Skewing ?? 

UWP supports Skewing with a **CompositeTransform**, but how can this be done with composition?

[https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.SkewTransform](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.SkewTransform)

**Comment by sohchatt** [comment]
You can apply a Skew transform to a Visual, Shape, Brush, etc. by modifying its [TransformMatrix](https://docs.microsoft.com/uwp/api/windows.ui.composition.visual.transformmatrix#Windows_UI_Composition_Visual_TransformMatrix) property.

Let's say you want to apply it to a Visual's 4x4 matrix:

```C#
            float skewYX = 0;
            float skewYZ = 0;
            float skewXY = 1;
            float skewXZ = 0;
            float skewZY = 0;
            float skewZX = 0;

            var skew = new Matrix4x4(1, skewYX, skewZX, 0,
                                     skewXY, 1, skewZY, 0,
                                     skewXZ, skewYZ, 1, 0,
                                     0, 0, 0, 1);

            visual.TransformMatrix = skew;
```

If you wish to animate the Skew, you can do so by setting up an [ExpressionAnimation](https://docs.microsoft.com/windows/uwp/composition/relation-animations) on the TransformMatrix with the relevant matrix elements configured as animated Paramaters.

Restricting this example to a 2D skew:

```C#
            // Insert scalar properties into a PropertySet for animated matrix entries 
            visual.Properties.InsertScalar("skewX", 0);
            visual.Properties.InsertScalar("skewY", 0);

            // Create ExpressionAnimation to target TransformMatrix property
            var expression = c.CreateExpressionAnimation("Matrix4x4(1, visual.skewY, 0, 0, " +
                                                                   "visual.skewX, 1, 0, 0, " +
                                                                   "0, 0, 1, 0, " +
                                                                   "0, 0, 0, 1)");

            // Set reference paramter 
            expression.SetReferenceParameter("visual", visual);

            // Basic scalar animation to target the skew entries
            var scalarAnim = c.CreateScalarKeyFrameAnimation();
            scalarAnim.InsertKeyFrame(.5f, 1);
            scalarAnim.InsertKeyFrame(1, 0);
            scalarAnim.Duration = TimeSpan.FromSeconds(2);
            scalarAnim.IterationBehavior = AnimationIterationBehavior.Forever;

            // Hook up animations to properties
            visual.StartAnimation("skewY", scalarAnim);
            visual.StartAnimation("TransformMatrix", expression);
```

**Comment by assassin316** [comment]
That's great! thanks for a detailed example @sohchatt

**Comment by assassin316** [comment]
Hi again @sohchatt, I'm trying to understand how the values between the composition layer and StoryBoards map to each other:

Using your code for a 2D skew, I set a **visual.skewX** value of **1** in the matrix, and also created a Storyboard with a **SkewTransform** using a value of **45** for **SkewX**. I ran the animations side by side to compare:

![1 - 45](https://user-images.githubusercontent.com/17514380/53362055-4f547480-3907-11e9-9c26-b223538aeb87.gif)

I then modified the values to be **2** for **visual.skewX** and **90** for **SkewX** of the **SkewTransform**:

![2 - 90](https://user-images.githubusercontent.com/17514380/53362118-7448e780-3907-11e9-920e-2ca83ab5be6c.gif)

My final question is: is there a way to do a mapping of values so that my **visual.skewX** can map to the "_degrees_" value of a **SkewTransform** (_which are from 0 - 360_) ???

**Comment by sohchatt** [comment]
Skew/ shear is a linear transformation such that 
```
  x' = x + M.y, and
  y' = y
```

represents a horizontal skew, where M is the skewFactor. You could think of the skewFactor as the slope of the vertical lines resulting from the transformation. This should help you construct the relation between skewFactor and skewAngle that you're looking for:

```
 skewFactor = tan(skewAngle)  // ... or cotangent, depending on how you're measuring skewAngle.
```

So, in your case, using the tangent function works out:

```
> tan(0) = 0
> tan(45) = 1
> tan(90) = inf
```
Here's some more reading in case you're interested: https://en.wikipedia.org/wiki/Shear_mapping#Definition

**Comment by assassin316** [comment]
Thanks again @sohchatt!! My final fix according to your response for proper mapping was the following:

    // Switch from degrees to radians then calculate the skew factor
    var dtr = Math.PI * angle / 180.0;
    var skew = Math.Tan(dtr);

They now map perfectly  :)

**Comment by daneuber** [comment]
Closing this issue since it appears to be resolved
