### ISSUE TITLE
Lag when using small CompositionGeometry and PointerDown/UpThemeAnimation

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/WindowsCompositionSamples#329]
## Issue Type

[x] Bug Report   
[ ] Feature Request   
[ ] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Current Behavior

I'm using CompositionGeometry (in my specific case lines) to draw some small animated icons within a ListView ItemTemplate.
Everything works great till I click on the items. At that point the app starts to lag till the ListViewItemPresenter pointer animations are fully executed.
This only happens with small shapes, in my case a 18x10px area.

## Expected Behavior

The app shouldn't lag.

## Steps to Reproduce (for bugs)

1.  Draw some small geometries within a ListView ItemTemplate (in my case I'm using a 18x10px visual).
2.  Launch the app and click on a item containing a geometry visual.
3.  Notice the lag while pointer animations are being executed.

##  Your Environment

* SDK #:  10.0.18362.0
* Operating System build # :  18362.86
* Visual Studio Version # : 16.0.3

**Comment by sohchatt** [comment]
@FrayxRulez Can you attach a minimal repro project so we can investigate the issue?

**Comment by FrayxRulez** [comment]
Sure thing, here you go: [CompositionIssue.zip](https://github.com/microsoft/WindowsCompositionSamples/files/3170565/CompositionIssue.zip)

**Comment by FrayxRulez** [comment]
Might be useful to know that scaling up the Visual would make the problem disappear (but it isn’t a solution of course, as I need the original size)

**Comment by sohchatt** [comment]
@FrayxRulez thanks for the repro and bringing this issue to our attention: it is indeed manifest when transforms from the pointeranimation are applied to the ShapeVisual. We've added this bug to our internal backlog and will fix it for the next update.

In the meantime, as temporary workaround you can disable the tilt animation by editing the control’s template. For instance, in the Visual Studio designer:
* right-click the control and select Edit Template -> Edit Current or Edit a Copy
* remove any instances of \<PointerDownThemeAnimation /> and \<PointerUpThemeAnimation /> in the control’s VisualStates

**Comment by FrayxRulez** [comment]
Sadly this won’t apply to my case as editing the ListViewItem style would compromise virtualization and I’m dealing with really long lists of items, but I found a sorta of workaround myself, so all good. 

Thanks for the fast investigation, will wait for the fix for future scenarios! (Sorry for closing and reopening, completely misclicked)

**Comment by FrayxRulez** [comment]
This is fixed on 2004.
