### ISSUE TITLE
Question about Translation property

### ISSUE THREAD

**Issue by HppZ** [microsoft/WindowsCompositionSamples#335]
why don't you just add Translation property on Visual?
and `ElementCompositionPreview.SetIsTranslationEnabled` this API looks strange.

`visual.StartAnimation("Translation.Y", animation);` since there is no Translation on Visual, why we can StartAnimation on Translation.Y?

**Comment by Massimo37** [comment]
Read about it here:

https://github.com/Microsoft/WindowsCompositionSamples/issues/145#issuecomment-240457826

and here (at the bottom, Translation Property section):

https://blogs.windows.com/windowsdeveloper/2017/06/22/sweet-ui-made-possible-easy-windows-ui-windows-10-creators-update/

This was added after Composition came out. That is why Offset exists alongside Translation. Translation does not exist on a Visual, `SetIsTranslationEnabled` injects the property instead.

**Comment by HppZ** [comment]
thanks @Massimo37

**Comment by Massimo37** [comment]
👍
