### ISSUE TITLE
[Question] How to achieve this effect?

### ISSUE THREAD

**Issue by HppZ** [microsoft/WindowsCompositionSamples#337]
https://stackoverflow.com/questions/49718377/dropshadow-with-image-blur-uwp

**Comment by HppZ** [comment]
from Groove Music:
![image](https://user-images.githubusercontent.com/12285582/63915217-07560c00-ca68-11e9-89e9-557dd738da3b.png)

**Comment by HppZ** [comment]
![image](https://user-images.githubusercontent.com/12285582/64420378-c0a08b80-d0d1-11e9-9724-8faab7ea30c7.png)

**Comment by assassin316** [comment]
I think you're looking for this control:

https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/dropshadowpanel

**Comment by HppZ** [comment]
this shadow is not solidcolorbrush, it is generated from that image.

![image](https://user-images.githubusercontent.com/12285582/65646834-00062c00-e02f-11e9-954e-c28a191d897c.png)

**Comment by daneuber** [comment]
Hi @HppZ we'd recommend using Win2d to pre-blur the image, put that blurred surface in a visual, and parent that to the visual tree so that it's behind your image. Could you give that a try and see if you're able to get the effect you're looking for?

**Comment by ratishphilip** [comment]
I have implemented this effect in the ColorShadow control in CompositionProToolkit v1.0.1. Here are the [details](https://wpfspark.wordpress.com/2020/05/29/compositionprotoolkit-v1-0-released/).
