### ISSUE TITLE
A little doubt about about code in ThumbnailLighting.xaml.cs

### ISSUE THREAD

**Issue by songshizhao** [microsoft/WindowsCompositionSamples#342]
I want to adapt your code to my own project, but in code 
[WindowsCompositionSamples/SampleGallery/Samples/SDK/14393/ThumbnailLighting/ThumbnailLighting.xaml.cs](https://github.com/microsoft/WindowsCompositionSamples/blob/4086e727f08714bec3520ff1a1782c5cc822f650/SampleGallery/Samples/SDK%2014393/ThumbnailLighting/ThumbnailLighting.xaml.cs)
I feel confused about the code:
in **Page_loaded** event there is a call for **UpdateEffectBrush()**;
and then in **UpdateEffectBrush()** there is a call for **SetImageEffect(image)**
and then in **SetImageEffect** first Code:
**CompositionEffectBrush brush = _effectFactory.CreateBrush();**
problem is "_effectFactory" is an object without an instance.
Before this code I did not find any instantiations of this object.
Where did you complete the initialization before **Page_loaded**
Can you answer my confusion, Thank you!

**Comment by kevinguo305** [comment]
_effectFactory is created in the method UpdateLightingEffect() through _compositor.CreateEffectFactor(CompositeEffect) which gets called when the lighting selection combobox changes.

Let me know if this answers your question!

**Comment by salomen99** [comment]
izin verilmiştir :)

**Comment by songshizhao** [comment]
too long time 
properly right
did not check
thanks for your reply ：）
