### ISSUE TITLE
how to apply effects to any shape of area of an xaml element or visual element?

### ISSUE THREAD

**Issue by HppZ** [microsoft/WindowsCompositionSamples#345]
I want to apply effects to the blue area:
![image](https://user-images.githubusercontent.com/12285582/82022814-d41fdf80-96bf-11ea-8174-a73f22cba867.png)

**Comment by HppZ** [comment]
using a Path with its Fill property set to a effect brush is a solution, but any other solution available?

**Comment by hawkerm** [comment]
@ratishphilip's got a solution for this, see above and below this header here in his docs: https://github.com/ratishphilip/CompositionProToolkit#3-creating-masked-backdrop-brush-using-imasksurface
