### ISSUE TITLE
Use Windows Community Toolkit library instead of custom code

### ISSUE THREAD

**Issue by wldevries** [microsoft/WindowsCompositionSamples#348]
It would be helpful for new users to be pointed to the Windows Community Toolkit for extra functionality. The `ExpressionBuilder` is best used as a library instead of copying the code from this sample. Similarly a user is better off using a library for loading image brushes instead of the half native implementation that is hard to copy to your own solution.

Use functionality from the Windows Community Toolkit instead of the custom implementations for

* `ExpressionBuilder` -> `Microsoft.Toolkit.Uwp.UI.Animations.Expressions`
* `SamplesNative` and image loading -> `Microsoft.Toolkit.Uwp.UI.Media.Helpers.SurfaceLoader`

## Issue Type

[ ] Bug Report   
[x] Feature Request   
[ ] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Steps to Reproduce (for bugs)

1.  
2.  
3.  

##  Your Environment

* SDK #:  
* Operating System build # :  
* Visual Studio Version # :

**Comment by hawkerm** [comment]
I actually think the ExpressionBuilder code here is what's in the Toolkit. I don't know the history, but it'd certainly make sense to try and simplify the sample repo by using the Toolkit as a dependency.
