### ISSUE TITLE
Channel 9 links on Resources page re-direct to the same Microsoft Docs page

### ISSUE THREAD

**Issue by brnnnfx** [microsoft/WindowsCompositionSamples#354]
## Issue Type

[ ] Bug Report   
[ ] Feature Request   
[ ] Sample request  
[X] Documentation issue or request  
[ ] Other – Please describe:   

## Current Behavior
You're directed to https://docs.microsoft.com/en-us/teamblog/channel9joinedmicrosoftlearn instead of the relevant page

## Expected Behavior
The links should be updated so that they direct to the correct content 

OR

If the content no longer exists, to remove the links from the Resources page entirely

## Steps to Reproduce (for bugs)
1.  Navigate to the [Resources Wiki](https://github.com/microsoft/WindowsCompositionSamples/wiki/Resources) page
2.  Select the hyperlink `Build 2017 Talks on Channel 9 `

**Issue** - You're directed to https://docs.microsoft.com/en-us/teamblog/channel9joinedmicrosoftlearn instead of the relevant page

The following links are affected
- `Build 2017 Talks on Channel 9` https://aka.ms/windowsuibuild2017vids
- `Build 2015 Talks` https://channel9.msdn.com/Events/Build/2015?sort=recent&c=james-clarke&c=nick-waggoner&term=
- `Build 2016 Talks` https://channel9.msdn.com/Events/Build/2016?sort=status&direction=desc&c=anthony-young&c=chris-raubacher&c=dave-driver&c=james-clarke&c=kelly-renner&c=lindsay-kubasik&c=nick-waggoner&c=paul-gusmorino&c=Tim-Heuer&c=varun-shandilya&term=
- `Build 2017 Talks` https://channel9.msdn.com/Events/Build/2017?c%5B0%5D=Ashish-Shetty&c%5B1%5D=david-li&c%5B2%5D=james-clarke&c%5B3%5D=kelly-renner&c%5B4%5D=lindsay-kubasik&c%5B5%5D=nick-waggoner&c%5B6%5D=paul-gusmorino&c%5B7%5D=peter-felts
- `Build 2018 Talks` https://channel9.msdn.com/Events/Build/2018?sort=recent&c=chigusa-sansen&c=danielle-neuberger&c=paul-gusmorino&c=sohum-chatterjee&term=
- `2015 Visual Layer` https://channel9.msdn.com/Events/Windows/Developers-Guide-to-Windows-10-Version-1511/Creating-fluid-and-beautiful-UI-using-the-new-Visual-Layer
- `2017 Enhancing UX` https://channel9.msdn.com/events/Visual-Studio/Visual-Studio-2017-Launch/APP-105?term=david%20li&lang-en=true

**Comment by kevinguo305** [comment]
Thanks for the feedback! It seems that many of these videos have an expiration date which is why clicking on the link takes you to a generic page. I've removed the non-working links.
