### ISSUE TITLE
Docs on IAnimationObject and CompositionAnimation.SetExpressionReferenceParameter

### ISSUE THREAD

**Issue by trympet** [microsoft/WindowsCompositionSamples#363]
## Issue Type

[ ] Bug Report   
[ ] Feature Request   
[ ] Sample request  
[x] Documentation issue or request  
[ ] Other – Please describe:   

## Request
There are no proper docs on IAnimationObject nor CompositionAnimation.SetExpressionReferenceParameter. What scenario are these intended to support?

**Comment by raymond-wh-leung** [comment]
Thanks for posting the question. IAnimationObject is to allow a custom object (that is backed by composition objects) to participate in ExpressionAnimations, by redirecting its properties to the underlying composition object. 

The doc has been updated at:
- https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.composition.ianimationobject?view=windows-app-sdk-1.2&branch=main
- https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.composition.compositionanimation.setexpressionreferenceparameter?view=windows-app-sdk-1.2&branch=main
